# site settings
title: Yuanzhao Zhang
subtitle: Santa Fe Institute
email: yzhang@schmidtsciencefellows.org
description: Research Homepage of Yuanzhao Zhang
bio: Complex Systems | Nonlinear Dynamics | Networks | AI for Science | Scientific Machine Learning
#| <br /> <a href="https://scholar.google.com/citations?user=xueImSMAAAAJ&hl=en">Google Scholar</a> | <a href="https://www.researchgate.net/profile/Yuanzhao_Zhang">Research Gate</a> | <a href="https://orcid.org/0000-0002-2056-7755">ORCID</a>
#| <a href="assets/cv.pdf">Curriculum Vitae</a>
#baseurl: "/home" # the subpath of your site, e.g. /blog
url: "https://y-zhang.com" #"https://y-z-zhang.github.io" # the base hostname & protocol for your site
author: Yuanzhao Zhang
street_address:
city:
state:
zip_code:
country:
phone:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 14

# social settings
500px_url:
facebook_url:
github_url: https://github.com/y-z-zhang
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url: https://twitter.com/YuanzhaoZhang

# build settings
markdown: kramdown

sass:
  style: compressed

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
